### ISSUE TITLE
Imports are broken since 6.0.8 on Node 13.5 and 13.6

### ISSUE THREAD

**Issue by daverickdunn** [thenativeweb/uuidv4#181]
I could not import this module for Node 13.5 or 13.6. It works on 13.7, 13.4 and 12.10.

Since 13.7 is already out, you might not care, so go ahead and close this. I'm reporting for posterity at least.

- Windows 10 x64
- Node 13.5.0, 13.6.0

6.0.7 is the last version that works for me.

On 6.0.8 - 6.1.1 it throws:

```
internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for '...\node_modules\uuidv4\node_modules\uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (...\node_modules\uuidv4\build\lib\uuidv4.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}
```

On 6.1.1 - 6.2.0 it throws:

```
...\node_modules\uuidv4\node_modules\uuid\dist\esm-browser\index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (...\node_modules\uuidv4\build\lib\uuidv4.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
```

**Comment by goloroden** [comment]
Thanks for bringing up this issue!

However, we always only support the current LTS version (i.e., right now Node.js 12.x, and 14.x starting in October), so we haven't put any effort into figuring out whether the `uuidv4` module works with 13.x. Sorry for that.

Since it works again with 13.7, we would – as you already suggested – simply ignore this issue.

Hence I am going to close it. I hope you're fine with this.

**Comment by daverickdunn** [comment]
No problem, I already had the guts of the ticket written before I updated my Node version, so as I said, just leaving it here for others.
